### ISSUE TITLE
Path missing to detect hdf5 

### ISSUE THREAD

**Issue by aengdahly** [jokervTv/auto-install-WRFV4#5]
Hi!
I wanted to ask you if it is necessary to have the variable HDF5, if it was installed. 

```
Configure WRF: 34. (dmpar) GNU(gfortran/gcc)
checking for perl5... no
checking for perl... found /usr/bin/perl (perl)
Will use NETCDF in dir: /root/.WRF_MPAS_LIB/NETCDF-4.7.0
**HDF5 not set in environment. Will configure WRF for use without.**
PHDF5 not set in environment. Will configure WRF for use without.
```

Maybe you need:
export HDF5=$LIB_INSTALL_DIR/$HDF5_VERSION
in your .bashrc?

**Comment by yongpz** [comment]
Hi,

As far as I know, WRF will output files in netcdf format and netcdf requires hdf5, I follow it. So It still work well here, without reading the 'HDF5'.

But I don't know the specific difference between WRF using HDF5 and not. I would be very grateful if you could tell me.

Thank you for your suggestion, I will add it.

**Comment by yongpz** [comment]
solved, thanks
