### ISSUE TITLE
4.6版本能更新吗

### ISSUE THREAD

**Issue by HongLouyemeng** [jokervTv/auto-install-WRFV4#6]
我想要安装4.6版本的，老哥未来会更新这个仓库吗

**Comment by yongpz** [comment]
周末更新

**Comment by yongpz** [comment]
未来会更新，主要是有时候会忘记我还在维护这个库哈哈哈哈

**Comment by HongLouyemeng** [comment]
> 未来会更新，主要是有时候会忘记我还在维护这个库哈哈哈哈

可以可以，点赞

**Comment by yongpz** [comment]
```shell
bash -c "$(curl -fsSL https://raw.githubusercontent.com/jokervTv/auto-install-WRFV4/dev/autoInstall.sh)"
```

试试安装 4.6.0 行了不

**Comment by HongLouyemeng** [comment]
> ```shell
> bash -c "$(curl -fsSL https://raw.githubusercontent.com/jokervTv/auto-install-WRFV4/dev/autoInstall.sh)"
> ```
> 
> 试试安装 4.6.0 行了不

谢谢老哥，我下一个阶段开始会测试wrf4.6的安装，没想到更新这么快，哈哈QAQ

**Comment by HongLouyemeng** [comment]
可以安装4.6，未来会给出测试结论，目前假期中.jpg

**Comment by HongLouyemeng** [comment]
> ```shell
> bash -c "$(curl -fsSL https://raw.githubusercontent.com/jokervTv/auto-install-WRFV4/dev/autoInstall.sh)"
> ```
> 
> 试试安装 4.6.0 行了不

老哥我重装就报错了The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B219E535C964CA1，4.6.0可以运行

**Comment by HongLouyemeng** [comment]
> > ```shell
> > bash -c "$(curl -fsSL https://raw.githubusercontent.com/jokervTv/auto-install-WRFV4/dev/autoInstall.sh)"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 试试安装 4.6.0 行了不
> 
> 老哥我重装就报错了The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B219E535C964CA1，或者一直卡在0% [Connecting to repo.nordvpn.com (2a03:2880:f117:83:face:b00c:0:25de)]
。但4.6.0可以运行
