### ISSUE TITLE
老哥，我想用4.2版本了，但是ungrib.exe报错了QAQ

### ISSUE THREAD

**Issue by HongLouyemeng** [jokervTv/auto-install-WRFV4#7]
error while loading shared libraries: libjasper.so.4: cannot open shared object file: No such file or directory

**Comment by yongpz** [comment]
检查环境变量和安装日志才能确定错误，大概率安装失败了

**Comment by HongLouyemeng** [comment]
> 检查环境变量和安装日志才能确定错误，大概率安装失败了

收到
